"  If you don't understand a setting in here, just type ':h setting'.

let mapleader = "\<Space>"

" split vimrc and source vimrc
nmap <leader>vr :sp $MYVIMRC<cr>
nmap <leader>so :source $MYVIMRC<cr>

map <leader>d obinding.pry<esc>:w<cr>
map <leader>i mmgg=G'm
map <leader>h :nohlsearch<cr>

set nocompatible
set noswapfile

filetype off

" Make backspace behave in a sane manner.
set backspace=indent,eol,start

set tabstop=2 shiftwidth=2 expandtab

" Make numbers visible
set relativenumber

" highlight while searching and keep it there after the search
set incsearch
set hlsearch

" case insensitive pattern matching
set ignorecase
" overrides ignorecase if patten matching contains spaces
set smartcase

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'kien/ctrlp.vim'
Plugin 'altercation/vim-colors-solarized'

" All of your Plugins must be added before the following line
call vundle#end()

" Enable file type detection and do language-dependent indenting.
filetype plugin indent on

syntax on

" And plugins too.
filetype plugin plugin on

" Load colorscheme
set background=dark
colorscheme solarized

" Let ctrlp use git
let g:ctrlp_user_command = ['.git/', 'cd %s && git ls-files -co --exclude-standard']

autocmd BufWritePre * :%s/\s\+$//e
